### ISSUE TITLE
Raytracing shadows and reflections

### ISSUE THREAD

**Issue by torchesburn** [jmorton06/Lumos#118]
Just wondering whether there is any support for raytraced shadows and reflections?

Like for example: 
https://github.com/SaschaWillems/Vulkan/blob/master/examples/raytracingshadows/raytracingshadows.cpp

**Comment by jmorton06** [comment]
Would like to add something like that but I don't have a ray tracing capable GPU

**Comment by torchesburn** [comment]
Ive got an RTX 3070 and have been testing the Vulkan examples here:

https://github.com/SaschaWillems/Vulkan/tree/master/examples/raytracingshadows

and it works fine. 

Whats your GPU?

**Comment by jmorton06** [comment]
just a gtx 1060 :D
