### ISSUE TITLE
Some build steps in README.md are outdated

### ISSUE THREAD

**Issue by adriengivry** [jmorton06/Lumos#130]
**Describe the bug**
I tried to follow build steps on MacOS, but it seems like the build/ folder isn't generated. We should update the documentation to better reflect the current architecture.

**Expected behavior**
Documentation should be up-to-date.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma (M1 Pro Max)

**Additional context**

**Comment by jmorton06** [comment]
Thanks forgot to update that. Fixed in https://github.com/jmorton06/Lumos/commit/d2eec604d3843459d5b520276258d0135da8387c
