### ISSUE TITLE
 how can i build with opengl?

### ISSUE THREAD

**Issue by alexbanks-git** [jmorton06/Lumos#25]
cool project, I tried to build for Linux, but it crashes when I start Sandbox, because the vulkan is not initialized, there is a light library reactphysics3d for simulate physics, I would really like to see it in your project

**Comment by jmorton06** [comment]
Thank you :). Do you have Vulkan set up on your PC? I don’t work on Linux too much so haven’t tested it for a while. If you want to use OpenGL you need to change the value in the settings file in the sandbox folder. Set renderapi to 0.

**Comment by alexbanks-git** [comment]
I tried to change the value "Renderapi=0",
yes I installed a vulkan, but it looks like my hardware does not support it.

`

Vulkan Instance Version: 1.1.70

/build/vulkan-UL09PJ/vulkan-1.1.70+dfsg1/demos/vulkaninfo.c:2700: failed with VK_ERROR_INITIALIZATION_FAILED
lin@lin:~/Desktop/Lumos/bin/Debug$ ./Sandbox 
[17:12:50] LUMOS: Profiler Enabled
[17:12:50] LUMOS: Lumos Engine - Version 0.2.1
[17:12:50] LUMOS: Initialised JobSystem with [4 cores] [4 threads]
[17:12:50] LUMOS: Initializing System
[LUA] - Initialised Lua!
[17:12:50] LUMOS: Creating window - Title : Sandbox, Width : 1280, Height : 800
Segmentation fault (стек памяти сброшен на диск)`

**Comment by jmorton06** [comment]
Ah right sorry. I’ll try have a look when I get a chance. If OpenGL is selected the Vulkan stuff shouldn’t be touched

**Comment by alexbanks-git** [comment]
ok thanks i'll wait

**Comment by jmorton06** [comment]
I think the Segmentation fault is due to an error with file loading. Not sure why as it used to work :/

**Comment by alexbanks-git** [comment]
maybe the path to the folder with the resources does not match
in the project I did not find such a folder "/CoreTextures"
![deb](https://user-images.githubusercontent.com/40067057/66309710-f58f4080-e912-11e9-838b-764af6e75403.png)

**Comment by jmorton06** [comment]
There’s a virtual file system to map locations to the actual file path.

VFS::Get()->Mount("CoreTextures", root + "/lumos/res/textures");

So it should map it to the right directory

**Comment by alexbanks-git** [comment]
:)

**Comment by alexbanks-git** [comment]
I think I have crashes caused by shaders.
changed a few lines:
GLFWWindow.cpp 
` //SetIcon("/CoreTextures/icon.png");` 
and add:
`glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);`

GLIMGUIRenderer.cpp
`ImGui_ImplOpenGL3_Init("#version 330");`

![Снимок экрана от 2019-10-08 11-14-13](https://user-images.githubusercontent.com/40067057/66378815-f8df0680-e9bc-11e9-8cb2-98f938ae58f0.png)

**Comment by jmorton06** [comment]
Ah great. Thank you for finding the issue. I'll add them changes in. (The artifacts on the spheres is some other issue somewhere with opengl :) )

**Comment by alexbanks-git** [comment]
I have no idea what I'm doing. But
has some effect if I change TextureAttachment.
![Снимок экрана от 2019-10-08 16-32-18](https://user-images.githubusercontent.com/40067057/66400372-052d8880-e9ea-11e9-9ec7-09682e23c9f1.png)

**Comment by jmorton06** [comment]
That issue should be fixed on the DEV branch now :)

**Comment by alexbanks-git** [comment]
excellent, because I don’t understand anything in shaders, I suffered with them in a test project))
(version 410+ changed to 330, and the model is invisible, but I thought the loader was fooling me..)

**Comment by jmorton06** [comment]
Haha yeah can be just a very small problem and you end with a blank screen. RenderDoc is good for shader problems

**Comment by alexbanks-git** [comment]
GlShader.cpp: line 926;(master)
`void GLShader::SetUniformMat4(u32 location, const Maths::Matrix4& matrix)
{
 //if here  Maths::ValuePointer(matrix) then i have crush
GLCall(glUniformMatrix4fv(location, 1, GL_FALSE /*GLTRUE*/, &matrix.values[0]));
}`

**Comment by alexbanks-git** [comment]
GlShader.cpp: line 926;(master)
`void GLShader::SetUniformMat4(u32 location, const Maths::Matrix4& matrix)`
`{`
 //if here  Maths::ValuePointer(matrix) then i have crush
`GLCall(glUniformMatrix4fv(location, 1, GL_FALSE /*GLTRUE*/, &matrix.values[0]));`
`}`

**Comment by jmorton06** [comment]
I think that should be fixed now. Sorry it's not very stable
