### ISSUE TITLE
How did you style imgui so nicely?

### ISSUE THREAD

**Issue by NotAPenguin0** [jmorton06/Lumos#35]
I saw your screenshot, and was wondering what changes you made to imgui's styling to accomplish this look.

**Comment by jmorton06** [comment]
I think the main thing that improved it was the font. https://github.com/jmorton06/Lumos/blob/master/Lumos/res/textures/Roboto-Medium.ttf.
https://github.com/jmorton06/Lumos/blob/master/Lumos/res/fonts/fa-solid-900.ttf - for the icons.

Then using the dark theme in : https://github.com/jmorton06/Lumos/blob/master/Lumos/src/ImGui/ImGuiHelpers.cpp

**Comment by NotAPenguin0** [comment]
Thanks a lot, I'll check it out

**Comment by jmorton06** [comment]
No problem :)
