### ISSUE TITLE
Put your project in the EnTT in Action list

### ISSUE THREAD

**Issue by skypjack** [jmorton06/Lumos#51]
Hi, sorry to bother you, I'm the author of `EnTT`.

I found your project and I think it's very interesting in many (many!) ways. Probably you already know that but I'm also trying to give the users of `EnTT` a few examples from which to take inspiration when they move their first steps.

Since I usually prefer to ask before referring to other projects, here I am.
What do you think about putting your repo in [the list of projects](https://github.com/skypjack/entt/wiki/EnTT-in-Action) _made with `EnTT`_?
I've already written this down but I haven't published the updated list yet. I'm asking here and there if users are fine with having their projects linked before to proceed.
If it's fine for you, you can just close the issue with a :+1: I'd be glad to have your project in that list.

Thanks anyway. :+1:

**Comment by jmorton06** [comment]
Hi, thanks very much. I really appreciate your comments. That would be great, I’d be happy for it to be added to the list. 

I found Entt very helpful and it improved my work a lot very easily so thank you!

Cheers 😄
