### ISSUE TITLE
Lumos::OS::Instance()->GetExecutablePath()  return nullptr

### ISSUE THREAD

**Issue by Molers** [jmorton06/Lumos#53]
Hello I am a beginner in Programming,and seems I have a problem.
my platform is windows and i download the github file .
click /scripts/GenerateVS19.bat .
then in /build ,i have a lumos.sln. 
It seems fine until now . i use VS2019 Debug x64 
when the project is running ,the problem is 
In SandBox Init()

**const String root = Lumos::OS::Instance()->GetExecutablePath();//ROOT_DIR;**
return **nullptr** and **Read access violation**。

 I don't know why .

**Comment by jmorton06** [comment]
Hey sorry about that. I’ve been mainly trying to get everything to work on iOS and I have left that change in by mistake. I’ll fix it a bit later on

**Comment by jmorton06** [comment]
Replacing that line with : 
const String root = ROOT_DIR;
		VFS::Get()->Mount("Meshes", root + "/Sandbox/res/meshes");
		VFS::Get()->Mount("Textures", root + "/Sandbox/res/textures");
		VFS::Get()->Mount("Sounds", root + "/Sandbox/res/sounds");

Should fix it for now

**Comment by Molers** [comment]
OK,it could run now ,Thank you

**Comment by jmorton06** [comment]
Okay great. Let me know if you have any other issues or questions
