### ISSUE TITLE
Getting renderdoc to work

### ISSUE THREAD

**Issue by redorav** [jmorton06/Lumos#65]
**Describe the bug**
I'm trying to get a capture from the engine to learn a little bit how it works

**To Reproduce**
I have compiled it on VS2019 and tried to hook renderdoc 1.11 up to it. I have also tried defining LUMOS_DEBUG and m_RenderDocLayer = true, but they all fail in some way or another. Launching through renderdoc fails creating the device, setting the renderdoc extension fails creating the instance.

**Expected behavior**
To be able to launch renderdoc and get a capture.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10, Vulkan backend (OpenGL fails but loading some file, I haven't investigated much deeper)

**Additional context**
It will crash creating the swapchain but that's because the device is null.

Thanks!

**Comment by jmorton06** [comment]
Not sure about this one sorry. It was working not long ago. I’ll try and have a look

**Comment by jmorton06** [comment]
Latest dev commit worked with renderdoc 1.11 with both OpenGL and Vulkan on windows. No need to define LUMOS_DEBUG or m_RenderDocLayer = true

**Comment by jmorton06** [comment]
Now in master - Let me know if its still not working

**Comment by redorav** [comment]
Works now, thank you :)
