### ISSUE TITLE
LumosEditor segfaults

### ISSUE THREAD

**Issue by Derailedzack** [jmorton06/Lumos#77]
**Describe the bug**
The lumos editor segfaults in cereal::JSONInputArchive::LoadValue
**To Reproduce**
Run the editor
Wait for the editor to load the model
**Expected behavior**
Editor shouldn't segfault
**Screenshots**

Thread 1 "LumosEditor" received signal SIGSEGV, Segmentation fault.
0x000055555568dc1c in cereal::JSONInputArchive::loadValue (
    this=0x7fffffffd8d0, val=<error reading variable>)
--Type <RET> for more, q to quit, c to continue without paging--
    at ../Lumos/External/cereal/include/cereal/archives/json.hpp:649
649	      void loadValue(float & val)       { search(); val = static_cast<float>(itsIteratorStack.back().value().GetDouble()); ++itsIteratorStack.back(); }

**Desktop (please complete the following information):**
- Pop OS 20.04
**Additional context**

**Comment by Derailedzack** [comment]
Is this bug invaild?

**Comment by jmorton06** [comment]
Thanks. Ill look into it. Might be linux only

**Comment by Derailedzack** [comment]
I could do some testing on windows

**Comment by jmorton06** [comment]
Ah okay thanks for checking on windows too. Not sure why it’s crashing. I’ve seen this type of crash when it tries to load an old scene after the saving scene has updated and loads new things

**Comment by Derailedzack** [comment]
Somehow the one I compiled broke so I had to recompile it.
