### ISSUE TITLE
A binary file should be there...

### ISSUE THREAD

**Issue by Light-Lens** [jmorton06/Lumos#79]
I like this Engine and someday i will probably use it to make some games but i think that generating the VS .sln file and then opening VS, then compiling and running it is a pretty long and complex way (It's just my opinion as i'm not as used to VS a lot).

You should probably upload a simple binary file which will be a bit useful for some people. By doing that some people will just try the current features out, if there's some issue they will either clone the source code or create a Github issue.

But no problem as this engine is pretty good and has a lot of potential in it.

**Comment by jmorton06** [comment]
Thank you. Yeah I'd like to do that. I just need to sort how the assets are loaded since the build process sets the directory which isn't ideal

**Comment by Light-Lens** [comment]
> Thank you. Yeah I'd like to do that. I just need to sort how the assets are loaded since the build process sets the directory which isn't ideal

Cool! I think that now you might remember this in future so, it's time to close this issue.
