### ISSUE TITLE
readme git clone recursive and premake5

### ISSUE THREAD

**Issue by danilw** [jmorton06/Lumos#93]
https://github.com/jmorton06/Lumos/blob/master/README.md

```
git clone --recursive https://github.com/jmorton06/Lumos.git
```

Tools/premake5 has wrong architecture for x86-64 CPU, Tools/linux/premake5 works

```
Tools/linux/premake5 gmake2
```

**Comment by jmorton06** [comment]
Thank you. Will fix in the readme
